### PR TITLE
fixed #17, updated gradle version

### LINKED ISSUE #17: Crash 1 18 2
https://pastebin.com/muzaWU5k

### PR DESCRIPTION
**Pull request by CCr4ft3r**

### CODE REVIEW

**Comment by CCr4ft3r** [comment]
I grant ldtteam the following:
- A license to use your contributions to the ldtteam organization (https://github.com/ldtteam) repositories, under the GPLv3 license.
- The right to re-license your contributions as they see fit.
- This is a legally binding copyright assignment to the ldtteam project for contributions.

**Comment by Thodor12** [comment]
You don't write it, you have to sign the CLA itself, otherwise the PR cannot be merged

**Comment by marchermans** [comment]
Additionally you need to run the update command for the Gradle wrapper.

**Comment by marchermans** [comment]
Additionally #17 has been fixed for a long while.

**Comment by Thodor12** [comment]
@marchermans he means to backport it to 1.18.2, as I think you stated it's only fixed in recent 1.19.x versions

**Comment by CCr4ft3r** [comment]
I don't like to give data to other applications just to being able to contribute to an open source project. Seems uncommon to me. 
So merging would not be possible without signing via CLA assistant?
If you cannot or don't want to accept my writen agreement I'm fine with you closing this pull request.

**Comment by Atlantispy** [comment]
This fix for 1.18 would be greatly appreciated!

**Comment by marchermans** [comment]
Ah yeah no.

**Comment by Atlantispy** [comment]
If you don't accept this PR could you please consider porting the fix on your end?

**Comment by Thodor12** [comment]
All you do is basically give your consent that to our contribution guidelines, you only login with your Github account (which we already know who you are)

**Comment by CCr4ft3r** [comment]
Knowing my GithHub account is fine. But GitHub states that CLA assistant wants to access my email address. This shouldn't be already exposed

**Comment by CCr4ft3r** [comment]
I can absolutely understand the purpose of a CLA but imho it should be also possible to opt in via a written agreement.

**Comment by Thodor12** [comment]
It has to be done on CLA assistant, it's all too easy to just delete a comment and say "but I never agreed to this".
If you sign it, it's known to a third party (which is also that license/cla check that says pending), that then becomes green, which means the PR is ready.

It's totally fine if you don't want to agree to the CLA, but that means your PR will not be merged.
And we will not give a guarantee someone else will do it, and I think @marchermans already said no to merging this anyway, and he's the eventual maintainer of this project.

**Comment by CCr4ft3r** [comment]
I was just wondering, because I actually thought that this is automatically specified and granted by the license of the project itself: https://github.com/ldtteam/PerViamInvenire/blob/version/latest/LICENSE
Correct me if I'm wrong about that.

Since GPL 3 states that derivative work must be distributed under the same or equivalent license terms no contributor would be able to insist on something else for their changes even though when they didn't agreed to it explicitly.

But I'm fine with that.

**Pull request closed without merging**
